# Generated by Django 6.1.1 on 2026-09-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='posts/photos/')),
                ('video', models.FileField(blank=True, null=True, upload_to='posts/videos/')),
                ('cr_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
